---
- name: Configure OpenSSH server
  block:

    - name: Test the SSH server configuration
      block:

        - name: Audit SSH and generate JSON output
          ansible.builtin.command: ssh-audit -j localhost
          check_mode: false
          changed_when: false
          register: ssh_audit_json

        - name: Set a fact for the SSH audit results
          ansible.builtin.set_fact:
            ssh_audit: "{{ ssh_audit_json.stdout | from_json }}"

        - name: Debug the SSH audit results
          ansible.builtin.debug:
            var: ssh_audit
            verbosity: 2

        - name: Set a fact for the version of OpenSSH installed
          ansible.builtin.set_fact:
            ssh_version: "{{ ssh_audit.banner.software | regex_replace('^OpenSSH_') | regex_replace('p1$') }}"

        - name: Write the proposed config to a test file
          ansible.builtin.template:
            src: templates/sshd_config.j2
            dest: /etc/ssh/.sshd_config.ansible.test
            mode: "0600"
            owner: root
            group: root
            validate: /usr/sbin/sshd -t -dd -f %s
          register: ssh_config_test

      rescue:

        - name: Print standard error from the test of the proposed configuration
          ansible.builtin.debug:
            var: ssh_config_test.stderr

        - name: Fail because the generated test sshd_config does not validate
          ansible.builtin.fail:
            msg:
              - "The proposed new SSH configuration did not validate, see the errors above."
              - "The failed configuration has been written to /etc/ssh/.sshd_config.new"

    - name: Apply the SSH server configuration
      block:

        - name: SSHD configuration file sshd_config in place
          ansible.builtin.template:
            src: templates/sshd_config.j2
            dest: /etc/ssh/sshd_config
            mode: "0644"
            owner: root
            group: root
            validate: /usr/sbin/sshd -t -f %s
            backup: true
          register: ssh_config
          notify: restart ssh

      rescue:

        - name: Non-valid sshd_config written to /etc/ssh/.sshd_config.broken
          ansible.builtin.template:
            src: templates/sshd_config.j2
            dest: /etc/ssh/.sshd_config.broken
            mode: "0600"
            owner: root
            group: root

        - name: Print standard error from the test of the proposed configuration
          ansible.builtin.debug:
            var: ssh_config.stderr

        - name: Fail because the generated sshd_config does not validate
          ansible.builtin.fail:
            msg:
              - "/etc/ssh/sshd_config has not been updated, a non-valid SSH server config has not been applied."
              - "The non-valid SSH server config has been written to /etc/ssh/.sshd_config.broken"

    - name: Flush handlers to restart SSH if the configuration has changed
      ansible.builtin.meta: flush_handlers
      when: (ssh_config is defined) and (ssh_config.changed | bool)

  tags:
    - ssh
...
