---
- name: Check that SSH host keys are present
  block:

    - name: "Stat {{ ssh_host_key_path }}"
      stat:
        path: "{{ ssh_host_key_path }}"
      register: ssh_host_key_state
      notify: "{% if ssh_host_key_state is defined and not ssh_host_key_state.stat.exists %}reconfigure ssh{% else %}[]{% endif %}"

  tags:
    - ssh
...
