---
- name: Check that SSH host keys are present
  block:

    - name: "Stat {{ ssh_host_key_path }}"
      ansible.builtin.stat:
        path: "{{ ssh_host_key_path }}"
      register: ssh_host_key_state

    - name: Reconfigure SSH
      ansible.builtin.command: dpkg-reconfigure openssh-server
      when: not ssh_host_key_state.stat.exists
      notify: restart ssh

  tags:
    - ssh
...
