# Copyright 2019-2024 Chris Croome
#
# This file is part of the Webarchitects OpenSSH Ansible role.
#
# The Webarchitects OpenSSH Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects OpenSSH Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects OpenSSH Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: OpenSSH server present
  block:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: not ansible_check_mode | bool

    - name: Run apt-cache policy
      ansible.builtin.command: apt-cache policy
      check_mode: false
      changed_when: false
      register: ssh_apt_cache_policy

    - name: OpenSSH packages present from backports
      ansible.builtin.apt:
        pkg:
          - openssh-client
          - openssh-server
          - openssh-sftp-server
        state: latest
        default_release: "{{ ansible_distribution_release }}-backports"
        install_recommends: true
      register: ssh_install_backports
      notify: Restart ssh
      when: ssh_apt_backports in ssh_apt_cache_policy.stdout

    - name: OpenSSH and related packages present
      ansible.builtin.apt:
        pkg:
          - libc-bin
          - kitty-terminfo
          - openssh-client
          - openssh-server
          - openssh-sftp-server
          - ssh-import-id
        state: present
        install_recommends: true
      register: ssh_install
      notify: Restart ssh

    - name: Stat /lib/systemd/system/ssh.service
      ansible.builtin.stat:
        path: /lib/systemd/system/ssh.service
      register: ssh_system_service

    - name: Stat /etc/systemd/system/multi-user.target.wants/ssh.service
      ansible.builtin.stat:
        path: /etc/systemd/system/multi-user.target.wants/ssh.service
      register: ssh_system_service_symlink

    - name: OpenSSH enabled and started
      ansible.builtin.systemd_service:
        name: ssh
        enabled: true
        state: started
      register: ssh_service
      when:
        - ssh_system_service.stat.exists | bool
        - ssh_system_service_symlink.stat.exists | bool

    - name: Restart SSH and re-run checks if when new packages are installed
      block:

        - name: Flush handlers to restart SSH if packages have been updated
          ansible.builtin.meta: flush_handlers

        - name: Run pre-update checks
          ansible.builtin.include_tasks: checks.yml
          vars:
            ssh_first_check: true

      when: >-
        ( ( ssh_install_backports is defined ) and
        ( ssh_install_backports.changed | bool ) ) or
        ( ( ssh_install is defined ) and
        ( ssh_install.changed | bool ) )

  tags:
    - ssh
...
