---
- name: Groups on the server
  shell: "getent group | awk -F: '{ print $1 }'"
  register: ssh_getent_group
  changed_when: false

- name: Variable set for groups
  set_fact:
    ssh_groups: "{{ ssh_getent_group.stdout_lines }}"

- name: Update sshd_config, test it, restat if test passes and restore previous config if not 

  block:

    - name: sshd_config in place
      template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        backup: yes
      register: ssh_config

    # If this fails the rescue tasks are executed
    - name: sshd_config tested
      command: sshd -t
      register: ssh_test

    - name: Restart SSH as configtest passed
      service:
        name: ssh
        state: restarted

  rescue:

    - name: Last sshd_config backup
      shell: ls /etc/ssh/sshd_config.* -tr | grep sshd_config | tail -n1
      register: ssh_config_backup

    - name: sshd_config backup restored
      command: "cp {{ ssh_config_backup.stdout }} /etc/ssh/sshd_config"

    - debug:
        msg: "Previous sshd_config restored due to errors with update: {{ ssh_test.stderr }}"
