# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects OpenSSH Ansible role.
#
# The Webarchitects OpenSSH Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects OpenSSH Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects OpenSSH Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Skip the tasks in this role as ssh is false
  ansible.builtin.debug:
    msg: "The ssh variable need to be true for the tasks in this role to run."
  when: not ssh | bool
  tags:
    - ssh

- name: Debug variables
  ansible.builtin.include_tasks: debug.yml
  when: ssh | bool
  tags:
    - ssh
    - ssh_debug

- name: Verify variables
  ansible.builtin.include_tasks: verify.yml
  when:
    - ssh | bool
    - ssh_verify | bool
    - ansible_version.full is version('2.11', '>=')
  tags:
    - ssh
    - ssh_verify

- name: Check variables
  ansible.builtin.include_tasks: checks.yml
  vars:
    ssh_first_check: true
  when: ssh | bool
  tags:
    - ssh
    - ssh_check

- name: SSH audit
  block:

    - name: Check the latest version of ssh-audit
      ansible.builtin.uri:
        url: https://github.com/jtesta/ssh-audit/releases/latest
        method: HEAD
        status_code: 302
        follow_redirects: none
      check_mode: false
      changed_when: false
      register: ssh_audit_headers

    - name: Debug ssh-audit latest headers
      ansible.builtin.debug:
        msg:
          - "Location: {{ ssh_audit_headers.location }}"
          - "Path: {{ ssh_audit_headers.location | urlsplit('path') }}"
          - "Version: {{ ssh_audit_headers.location | urlsplit('path') | basename | regex_replace('^v') }}"
        verbosity: 2

    - name: Set a fact for the latest version of ssh-audit
      ansible.builtin.set_fact:
        ssh_audit_version_latest: "{{ ssh_audit_headers.location | urlsplit('path') | basename | regex_replace('^v') }}"

    - name: Check if ssh-audit is installed
      ansible.builtin.command: which ssh-audit
      check_mode: false
      changed_when: false
      register: ssh_which_ssh_audit
      failed_when: ssh_which_ssh_audit.rc is not regex('^0|1$')

    - name: Check the insalled version of SSH Audit
      block:

        - name: Print ssh-audit -h
          ansible.builtin.command: ssh-audit -n -h
          check_mode: false
          changed_when: false
          register: ssh_audit_help

        - name: Set a fact for the installed version of ssh-audit
          ansible.builtin.set_fact:
            ssh_audit_installed_version: "{{ ssh_audit_help.stdout_lines[0].split(' ')[2] | regex_replace('^v') | regex_replace(',$') }}"

      when: ssh_which_ssh_audit.rc == 0

    - name: Include ssh-audit install tasks
      ansible.builtin.include_tasks: ssh_audit_install.yml
      when: (ssh_which_ssh_audit.rc == 1) or (ssh_audit_installed_version is not defined) or (ssh_audit_installed_version is version(ssh_audit_version_latest, '<'))

    - name: Include ssh-audit tasks
      ansible.builtin.include_tasks: ssh_audit.yml
      vars:
        ssh_first_check: true

  when: ssh | bool
  tags:
    - ssh
    - ssh_audit

- name: OpenSSH server present and configured
  block:

    - name: OpenSSH present
      ansible.builtin.include_tasks: install.yml

    - name: SSH host keys present
      ansible.builtin.include_tasks: host_key.yml
      loop: "{{ ssh_host_keys }}"
      loop_control:
        loop_var: ssh_host_key_path

    - name: SSH allow groups present
      ansible.builtin.group:
        name: "{{ ssh_allow_group }}"
        state: present
      loop: "{{ ssh_allow_groups }}"
      loop_control:
        loop_var: ssh_allow_group
      when: (ssh_allow_groups is defined) and (ssh_allow_groups != [])

    - name: Diffie-Hellman moduli which are less than 4000 bits absent
      ansible.builtin.lineinfile:
        path: /etc/ssh/moduli
        regexp: '^[0-9]{14}\ 2\ 6\ 100\ [1|2|3][0-9]{3}\ .*$'
        state: absent
        mode: "0644"
        owner: root
        group: root
      notify: restart ssh

    - name: OpenSSH server configured
      ansible.builtin.include_tasks: configure.yml

    - name: Run post-update checks
      ansible.builtin.include_tasks: checks.yml
      vars:
        ssh_first_check: false

    - name: Generate OpenSSH keypair for root user
      ansible.builtin.include_tasks: root.yml
      when: (ssh_root_keypair is defined) and (ssh_root_keypair | bool)

    - name: Include OpenSSH key pair generation for CI
      ansible.builtin.include_tasks: ci.yml
      when: (ssh_ci_ips is defined) and (ssh_ci_ips != [])

  when: ssh | bool
  tags:
    - ssh

- name: Include local OpenSSH client configuration tasks
  ansible.builtin.include_tasks: local_hosts.yml
  when:
    - ssh | bool
    - (ssh_local_hosts is defined) and (ssh_local_hosts | bool)
  tags:
    - ssh
    - ssh_local_hosts
    - ssh_fingerprint
...
