---
- name: Configure OpenSSH server
  block:

    - name: Packages present
      apt:
        pkg:
          - libc-bin
          - ssh-import-id
        state: present

    - name: Check ssh_allow_groups variable
      assert:
        that:
          - ssh_allow_groups | type_debug == "list"
      when: ssh_allow_groups is defined

    - name: Check ssh_deny_users variable
      assert:
        that:
          - ssh_deny_users | type_debug == "list"
      when: ssh_deny_users is defined

    - name: SSH allow groups present
      group:
        name: "{{ ssh_allow_group }}"
        state: present
      loop: "{{ ssh_allow_groups }}"
      loop_control:
        loop_var: ssh_allow_group
      when: ( ssh_allow_groups is defined ) and ( ssh_allow_groups != [] )

    - name: SSH ECDSA keypair for root present
      openssh_keypair:
        path: /root/.ssh/id_ed25519
        type: ed25519
        comment: "root@{{ inventory_hostname }}"
        state: present
        mode: "0600"
        owner: root
        group: root

    - name: Include SSH key pair generation for CI
      include_tasks: ci.yml
      when: ( ssh_ci_ips is defined ) and ( ssh_ci_ips != [] )

    - name: Remove Diffie-Hellman moduli which are less than 4000 bits
      lineinfile:
        path: /etc/ssh/moduli
        regexp: '^[0-9]{14}\ 2\ 6\ 100\ [1|2|3][0-9]{3}\ .*$'
        state: absent
        mode: "0644"
        owner: root
        group: root
      notify: restart ssh

    - name: sshd_config in place
      template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        mode: "0644"
        owner: root
        group: root
        validate: sshd -t -f %s
        backup: true
      notify: restart ssh

    - name: Loop through the SSH host keys
      include_tasks: host_key.yml
      loop: "{{ ssh_host_keys }}"
      loop_control:
        loop_var: ssh_host_key_path

  tags:
    - ssh
...
