---
- name: Configure OpenSSH server
  block:

    - name: Packages present
      apt:
        pkg:
          - libc-bin
          - ssh-import-id
        state: present

    - name: Groups present
      block:

        - name: Groups present
          group:
            name: "{{ group }}"
            state: present
          loop: "{{ ssh_groups }}"
          loop_control:
            loop_var: group

      when: ( ssh_groups is defined ) and ( ssh_groups != [] )

    - name: Register the groups on the server
      command: getent group
      register: ssh_getent_group
      changed_when: false
      check_mode: false

    - name: Set a variable for existing groups
      set_fact:
        ssh_groups: "{{ ssh_getent_group.stdout_lines | map('regex_replace', ':(.*)', '') | list }}"

    - name: SSH ECDSA keypair for root present
      command: ssh-keygen -q -t ed25519 -f /root/.ssh/id_ed25519 -q -N "" -C "root@{{ inventory_hostname }}"
      args:
        creates: /root/.ssh/id_ed25519

    - name: Include SSH key pair generation for CI
      include_tasks: ci.yml
      when: ( ssh_ci_ips is defined ) and ( ssh_ci_ips != [] )

    - name: Remove Diffie-Hellman moduli which are less than 4000 bits
      lineinfile:
        path: /etc/ssh/moduli
        regexp: '^[0-9]{14}\ 2\ 6\ 100\ [1|2|3][0-9]{3}\ .*$'
        state: absent
      notify: restart ssh

    - name: sshd_config in place
      template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        validate: sshd -t -f %s
        backup: true
      notify: restart ssh

    - name: Loop through the host keys
      include_tasks: host_key.yml
      loop: ssh_host_keys
      loop_control:
        loop_var: ssh_host_key_path

  tags:
    - ssh
...
