---
- name: Debug variables
  ansible.builtin.include_tasks: debug.yml
  tags:
    - ssh
    - ssh_debug

- name: Run checks
  ansible.builtin.include_tasks: checks.yml
  vars:
    ssh_first_check: true
  tags:
    - ssh
    - ssh_check

- name: Include ssh-audit install tasks
  ansible.builtin.include_tasks: ssh_audit.yml
  tags:
    - ssh
    - ssh_audit

- name: OpenSSH server present and configured
  block:

    - name: OpenSSH present
      ansible.builtin.include_tasks: install.yml

    - name: SSH host keys present
      ansible.builtin.include_tasks: host_key.yml
      loop: "{{ ssh_host_keys }}"
      loop_control:
        loop_var: ssh_host_key_path

    - name: SSH allow groups present
      ansible.builtin.group:
        name: "{{ ssh_allow_group }}"
        state: present
      loop: "{{ ssh_allow_groups }}"
      loop_control:
        loop_var: ssh_allow_group
      when: (ssh_allow_groups is defined) and (ssh_allow_groups != [])

    - name: Diffie-Hellman moduli which are less than 4000 bits absent
      ansible.builtin.lineinfile:
        path: /etc/ssh/moduli
        regexp: '^[0-9]{14}\ 2\ 6\ 100\ [1|2|3][0-9]{3}\ .*$'
        state: absent
        mode: "0644"
        owner: root
        group: root
      notify: restart ssh

    - name: OpenSSH server configured
      ansible.builtin.include_tasks: configure.yml

    - name: Run post-update checks
      ansible.builtin.include_tasks: checks.yml
      vars:
        ssh_first_check: false

    - name: Generate OpenSSH keypair for root user
      ansible.builtin.include_tasks: root.yml
      when: (ssh_root_keypair is defined) and (ssh_root_keypair | bool)

    - name: Include OpenSSH key pair generation for CI
      ansible.builtin.include_tasks: ci.yml
      when: (ssh_ci_ips is defined) and (ssh_ci_ips != [])

  tags:
    - ssh

- name: Include local OpenSSH client configuration tasks
  ansible.builtin.include_tasks: local_hosts.yml
  when: (ssh_local_hosts is defined) and (ssh_local_hosts | bool)
  tags:
    - ssh
    - ssh_local_hosts
    - ssh_fingerprint
...
