# Copyright 2019-2025 Chris Croome
#
# This file is part of the Webarchitects OpenSSH Ansible role.
#
# The Webarchitects OpenSSH Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects OpenSSH Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects OpenSSH Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Skip the tasks in this role as ssh is false
  ansible.builtin.debug:
    msg: "The ssh variable need to be true for the tasks in this role to run."
  when: ( ssh is not defined ) or ( not ssh | bool )
  tags:
    - ssh

- name: Variable checks
  block:

    - name: Include apt role local fact tasks
      ansible.builtin.include_role:
        name: apt
        tasks_from: local_facts.yml
      when: >-
        ( ansible_local.dpkg.arch is not defined ) or
        ( ansible_local.dpkg.installed is not defined ) or
        ( ansible_local.gpg.version is not defined ) or
        ( ansible_local.bash.path is not defined )

    - name: Debug variables
      ansible.builtin.include_tasks: debug.yml

    - name: Verify variables
      ansible.builtin.include_tasks: verify.yml
      when:
        - ssh_verify is defined
        - ssh_verify | bool
        - ansible_version.full is version('2.11', '>=')
      tags:
        - ssh_verify

    - name: Check variables
      ansible.builtin.include_tasks: checks.yml
      vars:
        ssh_first_check: true
      tags:
        - ssh_check

  when:
    - ssh is defined
    - ssh | bool
  tags:
    - ssh
    - ssh_debug

- name: SSH audit
  block:

    - name: Check the latest version of ssh-audit
      ansible.builtin.include_tasks: ssh_audit_version.yml

    - name: Include ssh-audit install tasks
      ansible.builtin.include_tasks: ssh_audit_install.yml
      when: >-
        ( ssh_which_ssh_audit.rc == 1 ) or
        ( ssh_audit_installed_version is not defined ) or
        ( ssh_audit_installed_version is version(ssh_audit_version_latest, '<') )

    - name: SSH Audit
      ansible.builtin.include_tasks: ssh_audit.yml
      vars:
        ssh_first_check: true
      when:
        - ssh_init is defined
        - ssh_init == "systemd"
        - ssh_listening_addresses is defined
        - ssh_listening_addresses != []
        - ssh_listening_ports is defined
        - ssh_listening_ports != []
        - ssh_audit_installed_version is defined
        - ssh_audit_installed_version is ansible.builtin.version('3.0.0', 'ge')

  when:
    - ssh is defined
    - ssh | bool
    - ssh_audit is defined
    - ssh_audit | bool
  tags:
    - ssh
    - ssh_audit

- name: OpenSSH server present and configured
  block:

    - name: OpenSSH present
      ansible.builtin.include_tasks: install.yml

    - name: SSH host keys present
      ansible.builtin.include_tasks: host_key.yml
      loop: "{{ ssh_host_keys }}"
      loop_control:
        loop_var: ssh_host_key
        label: "{{ ssh_host_key.name }}"

    - name: SSH allow groups present
      ansible.builtin.group:
        name: "{{ ssh_allow_group }}"
        state: present
      loop: "{{ ssh_allow_groups }}"
      loop_control:
        loop_var: ssh_allow_group
      when: (ssh_allow_groups is defined) and (ssh_allow_groups != [])

    - name: Diffie-Hellman moduli which are less than 4000 bits absent
      ansible.builtin.lineinfile:
        path: /etc/ssh/moduli
        regexp: '^[0-9]{14}\ 2\ 6\ 100\ [1|2|3][0-9]{3}\ .*$'
        state: absent
        mode: "0644"
        owner: root
        group: root
      notify: Restart sshd

    - name: OpenSSH server configured
      ansible.builtin.include_tasks: configure.yml

    - name: Generate OpenSSH keypair for root user
      ansible.builtin.include_tasks: root.yml
      when: (ssh_root_keypair is defined) and (ssh_root_keypair | bool)

    - name: Include OpenSSH key pair generation for CI
      ansible.builtin.include_tasks: ci.yml
      when: (ssh_ci_ips is defined) and (ssh_ci_ips != [])

    - name: Run post-update checks
      ansible.builtin.include_tasks: checks.yml
      vars:
        ssh_first_check: false

    - name: Include ssh-audit tasks
      ansible.builtin.include_tasks: ssh_audit.yml
      vars:
        ssh_first_check: false
      when:
        - ssh_audit is defined
        - ssh_audit | bool
        - ssh_init is defined
        - ssh_init == "systemd"
        - ssh_listening_addresses is defined
        - ssh_listening_addresses != []
        - ssh_listening_ports is defined
        - ssh_listening_ports != []
        - (ansible_facts | community.general.json_query(ssh_jpq.ssh_service)).status == "enabled"
        - (ansible_facts | community.general.json_query(ssh_jpq.ssh_service)).state == "running"

  when:
    - ssh is defined
    - ssh | bool
  tags:
    - ssh

- name: OpenSSH client configuration tasks
  block:

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Debug SSHD service status
      ansible.builtin.debug:
        msg: "{{ ansible_facts | community.general.json_query(ssh_jpq.ssh_service) }}"
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"

    - name: Include ssh-audit tasks
      ansible.builtin.include_tasks: ssh_audit_info.yml
      vars:
        ssh_audit_fail: false
        ssh_first_check: true
      when:
        - ssh_audit is defined
        - ssh_audit | bool
        - (ansible_facts | community.general.json_query(ssh_jpq.ssh_service)).status == "enabled"
        - (ansible_facts | community.general.json_query(ssh_jpq.ssh_service)).state == "running"
        - ssh_audit_results is not defined

    - name: Include local OpenSSH client configuration tasks
      ansible.builtin.include_tasks: local_hosts.yml

  when:
    - ssh is defined
    - ssh | bool
    - ssh_local_hosts is defined
    - ssh_local_hosts | bool
  tags:
    - ssh
    - ssh_local_hosts
    - ssh_fingerprint
...
