# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects OpenSSH Ansible role.
#
# The Webarchitects OpenSSH Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects OpenSSH Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects OpenSSH Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Generate keypair for root user
  block:

    - name: Root ~/.ssh directory present
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        mode: 0700
        owner: root
        group: root

    - name: Stat the root SSH ECDSA keypair
      ansible.builtin.stat:
        path: "{{ ssh_file }}"
      loop:
        - /root/.ssh/id_ed25519
        - /root/.ssh/id_ed25519.pub
      loop_control:
        loop_var: ssh_file
        label: "{{ ssh_file | basename }}"
      register: ssh_root_id_ed25519

    - name: SSH ECDSA keypair for root present
      community.crypto.openssh_keypair:
        path: /root/.ssh/id_ed25519
        type: ed25519
        comment: "root@{{ inventory_hostname }}"
        state: present
        mode: "0600"
        owner: root
        group: root
      when: >
         (ssh_root_id_ed25519.results[0].stat.exists is not defined or not ssh_root_id_ed25519.results[0].stat.exists) or
         (ssh_root_id_ed25519.results[0].stat.exists is not defined or not ssh_root_id_ed25519.results[1].stat.exists)
      register: ssh_root_id_ed25519

  tags:
    - ssh
...
