---
- name: Scan port for SSH public keys
  block:

    - name: Debug IP address
      ansible.builtin.debug:
        var: ip
        verbosity: 2
      when: ip is defined

    - name: Debug port
      ansible.builtin.debug:
        var: port
        verbosity: 2
      when: port is defined

    # https://man.openbsd.org/sshd.8#SSH_KNOWN_HOSTS_FILE_FORMAT
    - name: SSH key scan
      ansible.builtin.shell: >
        {% if port != 22 %}
        ssh-keyscan -p {{ port }} {{ ip }} | sed 's/^{{ ip }} /[{{ ip }}]:{{ port }} /' | sort
        {% else %}
        ssh-keyscan {{ ip }} | sort
        {% endif %}
      check_mode: false
      changed_when: false
      register: ssh_keyscan_command

    - name: Debug the key scan result
      ansible.builtin.debug:
        var: ssh_keyscan_command.stdout_lines
        verbosity: 2
      when: ssh_keyscan_command.stdout_lines is defined

    - name: Write any ssh-keyscan results to a local KnownHosts file if one is defined
      ansible.builtin.blockinfile:
        path: "{{ ssh_local_hosts_user_known_hosts_file }}"
        mode: 0600
        create: true
        # marker: "{mark} {{ ip }}:{{ port }}"
        marker: "{% if port == 22 %}# {mark} {{ ip }}{% else %}# {mark} {{ ip }}:{{ port }}{% endif %}"
        block: "{{ ssh_keyscan_command.stdout }}"
      become: false
      delegate_to: localhost
      when:
        - ssh_keyscan_command.stdout_lines is defined
        - ssh_local_hosts_user_known_hosts_file is defined

  tags:
    - ssh
    - ssh_keyscan
...
