---
- name: Scan SSH key fingerprints
  block:

    # TODO Perhaps loop through the ListenAddress rather then the Ansible
    #      default IP addresses?

    - name: Scan keys available on the default IPv4 address
      ansible.builtin.include_tasks: scan_key_address.yml
      vars:
        ip: "{{ ansible_default_ipv4.address }}"
      when: ansible_default_ipv4.address is defined

    - name: Scan keys available on the default IPv6 address
      ansible.builtin.include_tasks: scan_key_address.yml
      vars:
        ip: "{{ ansible_default_ipv6.address }}"
      when: ansible_default_ipv6.address is defined

  tags:
    - ssh
    - ssh_keyscan
...
