# Copyright 2019-2025 Chris Croome
#
# This file is part of the Webarchitects OpenSSH Ansible role.
#
# The Webarchitects OpenSSH Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects OpenSSH Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects OpenSSH Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Scan port for SSH public keys
  block:

    - name: Debug IP address
      ansible.builtin.debug:
        var: ssh_ip
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"
      when: ssh_ip is defined
      tags:
        - debug

    - name: Debug port
      ansible.builtin.debug:
        var: ssh_port
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"
      when: ssh_port is defined
      tags:
        - debug

    # https://man.openbsd.org/sshd.8#SSH_KNOWN_HOSTS_FILE_FORMAT
    - name: SSH key scan
      ansible.builtin.command: >-
        {% if ssh_port != 22 %}
        ssh-keyscan -p {{ ssh_port }} {{ ssh_ip }}
        {% else %}
        ssh-keyscan {{ ssh_ip }}
        {% endif %}
      check_mode: false
      changed_when: false
      register: ssh_keyscan_command

    - name: Debug the key scan standard error
      ansible.builtin.debug:
        var: ssh_keyscan_command.stderr_lines
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"
      when: ssh_keyscan_command.stderr_lines is defined
      tags:
        - debug

    - name: Debug the key scan standard out
      ansible.builtin.debug:
        var: ssh_keyscan_command.stdout_lines
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"
      when: ssh_keyscan_command.stdout_lines is defined
      tags:
        - debug

    - name: Write any ssh-keyscan results to a local KnownHosts file if one is defined
      ansible.builtin.blockinfile:
        path: "{{ ssh_local_hosts_user_known_hosts_file }}"
        mode: "0600"
        create: true
        marker: "{% if ssh_port == 22 %}# {mark} {{ ssh_ip }}{% else %}# {mark} {{ ssh_ip }}:{{ ssh_port }}{% endif %}"
        block: |
          {%- for ssh_fingerprint in ssh_keyscan_command.stdout_lines | sort -%}
          {%-     if ssh_fingerprint is not ansible.builtin.regex('^#') %}
          {{ ssh_fingerprint }}
          {%     endif -%}
          {%- endfor -%}
      become: false
      delegate_to: localhost
      when:
        - ssh_keyscan_command.stdout_lines is defined
        - ssh_local_hosts_user_known_hosts_file is defined

  tags:
    - ssh
    - ssh_local_hosts
...
