---
- name: Install ssh-audit from source
  block:

    - name: Check the latest version of ssh-audit
      ansible.builtin.uri:
        url: https://github.com/jtesta/ssh-audit/releases/latest
        method: HEAD
        status_code: 302
        follow_redirects: none
      check_mode: false
      changed_when: false
      register: ssh_audit_headers

    - name: Debug ssh-audit latest headers
      ansible.builtin.debug:
        msg:
          - "Location: {{ ssh_audit_headers.location }}"
          - "Path: {{ ssh_audit_headers.location | urlsplit('path') }}"
          - "Version: {{ ssh_audit_headers.location | urlsplit('path') | basename | regex_replace('^v') }}"
        verbosity: 2

    - name: Set a fact for the latest version of ssh-audit
      ansible.builtin.set_fact:
        ssh_audit_version_latest: "{{ ssh_audit_headers.location | urlsplit('path') | basename | regex_replace('^v') }}"

    - name: GPG public present
      ansible.builtin.copy:
        src: jtesta_2020-2025.asc
        dest: /root/jtesta_2020-2025.asc
        mode: 0600
        owner: root
        group: root

    - name: GPG present
      ansible.builtin.apt:
        pkg:
          - gpg
        state: present

    - name: GPG key imported
      ansible.builtin.command: gpg --import /root/jtesta_2020-2025.asc
      register: ssh_audit_gpg_import
      changed_when: ( "not changed" not in ssh_audit_gpg_import.stderr )

    - name: ssh-audit signature present
      ansible.builtin.get_url:
        url: "https://github.com/jtesta/ssh-audit/releases/download/v{{ ssh_audit_version_latest }}/ssh-audit-{{ ssh_audit_version_latest }}.tar.gz.sig"
        dest: "/usr/local/src/ssh-audit-{{ ssh_audit_version_latest }}.tar.gz.sig"
        mode: 0644
        owner: root
        group: root
     register: ssh_audit_sig_get_url

    - name: ssh-audit source present
      ansible.builtin.get_url:
        url: "https://github.com/jtesta/ssh-audit/releases/download/v{{ ssh_audit_version_latest }}/ssh-audit-{{ ssh_audit_version_latest }}.tar.gz"
        dest: "/usr/local/src/ssh-audit-{{ ssh_audit_version_latest }}.tar.gz"
        mode: 0644
        owner: root
        group: root
     register: ssh_audit_get_url

    - name: GPG signature verified
      ansible.builtin.command: "gpg --verify --logger-fd 1 /usr/local/src/ssh-audit-{{ ssh_audit_version_latest }}.tar.gz.sig"
      changed_when: false
      register: ssh_audit_gpg_check
      failed_when: ( "Good signature" not in ssh_audit_gpg_check.stdout )

    - name: ssh-audit source unarchived
      ansible.builtin.unarchive:
        src: "/usr/local/src/ssh-audit-{{ ssh_audit_version_latest }}.tar.gz"
        dest: "/usr/local/src"
        creates: "ssh-audit-{{ ssh_audit_version_latest }}"
        owner: root
        group: root
        remote_src: true

    - name: Check that ssh-audit works be running it with --help
      ansible.builtin.command: "python3 /usr/local/src/ssh-audit-{{ ssh_audit_version_latest }}/ssh-audit.py --help"

    - name: ssh-audit symlink in place
      ansible.builtin.file:
        state: link
        src: "/usr/local/src/ssh-audit-{{ ssh_audit_version_latest }}/ssh-audit.py"
        dest: /usr/local/bin/ssh-audit
        follow: false
        mode: 0777
        owner: root
        group: root

  tags:
    - ssh
    - ssh_audit
...
