---
- name: OpenSSH audit
  block:

    - name: Check if ssh-audit is available
      ansible.builtin.command: which ssh-audit
      check_mode: false
      changed_when: false
      register: ssh_which_ssh_audit
      failed_when: ssh_which_ssh_audit.rc is not regex('^0|1$')

    - name: Run ssh-audit for fail and info results
      block:

        - name: Audit SSH to check for failures
          ansible.builtin.command: ssh-audit -n -l fail localhost
          check_mode: false
          changed_when: false
          register: ssh_audit_fail
          failed_when: ssh_audit_fail.rc is not regex('0|2|3')

        - name: Print the SSH audit failure results if there are any
          ansible.builtin.debug:
            var: ssh_audit_fail.stdout_lines
          when: ssh_audit_fail.stdout_lines != []

        - name: Run SSH audit for info results
          block:

            - name: Audit SSH to check informational results
              ansible.builtin.command: ssh-audit -n -l info localhost
              check_mode: false
              changed_when: false
              register: ssh_audit_info
              failed_when:
                - not ssh_first_check | bool
                - ssh_audit_info.rc is not regex('0|2|3')

            - name: Debug the SSH audit info results
              ansible.builtin.debug:
                var: ssh_audit_info.stdout_lines

          when:
            - ssh_check_fail | bool
            - ssh_audit_fail.rc != 0

        - name: Fail due to ssh-audit results
          ansible.builtin.fail:
            msg:
              - "ssh-audit failed with the above results"
          when:
            - not ssh_first_check | bool
            - ssh_check_fail | bool
            - ssh_audit_fail.rc != 0

        - name: Audit SSH and generate JSON output
          ansible.builtin.command: ssh-audit -j localhost
          check_mode: false
          changed_when: false
          register: ssh_audit_json
          failed_when: ssh_audit_json.rc is not regex('0|2|3')

        - name: Set a fact for the SSH audit results
          ansible.builtin.set_fact:
            ssh_audit: "{{ ssh_audit_json.stdout | from_json }}"

        - name: Debug the SSH audit results
          ansible.builtin.debug:
            var: ssh_audit
            verbosity: 2

        - name: Set a fact for the version of OpenSSH installed
          ansible.builtin.set_fact:
            ssh_version: "{{ ssh_audit.banner.software | regex_replace('^OpenSSH_') | regex_replace('p1$') }}"

      when: ssh_which_ssh_audit.rc == 0

  tags:
    - ssh
    - ssh_audit
...
