# Copyright 2019-2025 Chris Croome
#
# This file is part of the Webarchitects OpenSSH Ansible role.
#
# The Webarchitects OpenSSH Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects OpenSSH Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects OpenSSH Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: SSH Audit
  block:

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Debug SSH service status
      ansible.builtin.debug:
        msg: "{{ ansible_facts | community.general.json_query(ssh_jpq.ssh_service) }}"
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"

    - name: Include ssh-audit info tasks
      ansible.builtin.include_tasks: ssh_audit_info.yml
      when:
        - (ansible_facts | community.general.json_query(ssh_jpq.ssh_service)).status == "enabled"
        - (ansible_facts | community.general.json_query(ssh_jpq.ssh_service)).state == "running"

    - name: SSH audit local policies present
      ansible.builtin.include_tasks: ssh_audit_policies.yml
      loop: "{{ ssh_audit_local_policies }}"
      loop_control:
        loop_var: ssh_audit_local_policy
        label: "{{ ssh_audit_local_policy.content.name }}"
      when:
        - ssh_audit_local_policies is defined
        - ssh_audit_local_policies != []

    - name: Check if the specified local SSH audit policy file is present
      ansible.builtin.stat:
        path: "{{ ssh_audit_local_policy_file }}"
      register: ssh_audit_local_policy_file_path
      when:
        - ssh_audit_local_policy_file is defined
        - ssh_audit_local_policy_file | length > 0

    - name: Set a fact for the local SSH audit policy file
      ansible.builtin.set_fact:
        ssh_audit_local_policy_present: true
      when:
        - ssh_audit_local_policy_file_path is defined
        - ssh_audit_local_policy_file_path.stat.exists | bool

    - name: Debug ssh_audit_local_policy_present
      ansible.builtin.debug:
        var: ssh_audit_local_policy_present
        verbosity: 1

    - name: Include ssh-audit local policy tasks
      ansible.builtin.include_tasks: ssh_audit_local.yml
      when:
        - ssh_audit_local_policy_present is defined
        - ssh_audit_local_policy_present | bool

    - name: Include ssh-audit builtin policy tasks
      ansible.builtin.include_tasks: ssh_audit_builtin.yml
      when: >-
        ( ssh_audit_local_policy_present is not defined ) or
        ( not ssh_audit_local_policy_present | bool )

  when:
    - ssh_audit is defined
    - ssh_audit | bool
  tags:
    - ssh
    - ssh_audit
...
