# Copyright 2019-2025 Chris Croome
#
# This file is part of the Webarchitects OpenSSH Ansible role.
#
# The Webarchitects OpenSSH Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects OpenSSH Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects OpenSSH Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Local ssh-audit policies
  block:

    - name: SSH audit policy directory present
      ansible.builtin.file:
        path: "{{ ssh_audit_local_policy.path | ansible.builtin.dirname }}"
        state: directory
        mode: "0755"
        owner: root
        group: root
      when:
        - ssh_audit_local_policy.state is defined
        - ssh_audit_local_policy.state == "present"
        - ssh_audit_local_policy.path is defined

    - name: SSH audit policy absent
      ansible.builtin.file:
        path: "{{ ssh_audit_local_policy.path }}"
        state: absent
      when:
        - ssh_audit_local_policy.state is defined
        - ssh_audit_local_policy.state == "absent"

    - name: Debug SSH audit policy present
      ansible.builtin.debug:
        msg: |-
          {% for ssh_audit_local_policy_content in ssh_audit_local_policy.content | ansible.builtin.dict2items %}
          {{ ssh_audit_local_policy_content.key }} = {% if ssh_audit_local_policy_content.key == "name" %}"{% endif %}{{ ssh_audit_local_policy_content.value }}{% if ssh_audit_local_policy_content.key == "name" %}"{% endif %}

          {% endfor %}
        verbosity: 1

    - name: SSH audit policy present
      ansible.builtin.template:
        src: ssh_audit_local_policy.txt.j2
        dest: "{{ ssh_audit_local_policy.path }}"
        mode: "0655"
        owner: root
        group: root
      when:
        - ssh_audit_local_policy.state is defined
        - ssh_audit_local_policy.state == "present"

  when:
    - ssh_audit is defined
    - ssh_audit | bool
  tags:
    - ssh_audit
    - ssh
...
