---
- name: SSH reconfigured
  command: dpkg-reconfigure openssh-server
  listen: reconfigure ssh
  tags:
    - ssh

- name: SSH restarted
  service:
    name: ssh
    state: restarted
  listen: restart ssh
  tags:
    - ssh
...
